# Generated by Django 4.2.2 on 2024-04-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_team_task_task_assigned_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incident_types',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=20, null=True),
        ),
    ]
