# Generated by Django 4.2.2 on 2024-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_task_incident_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='party',
            field=models.CharField(blank=True, default='Test', max_length=50, null=True),
        ),
    ]
