# Generated by Django 4.2.2 on 2024-04-05 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
