# Generated by Django 4.2.2 on 2024-04-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
